repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff

  - repo: https://github.com/python/mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies: ["pandas-stubs", "numpy"]
